name: snake_game
description: A retro 8-bit snake game built with Flutter and Flame.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # The core game engine
  flame: ^1.35.1

  # For 8-bit styled text/UI
  google_fonts: ^6.1.0

  shared_models: any
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - fonts/PressStart2P-Regular.ttf
  fonts:
    - family: PressStart2P
      fonts:
        - asset: fonts/PressStart2P-Regular.ttf
